repository:
  name: example-setup
  description: description of repo
  homepage: https://example.jkb.cloud
  private: false
  has_issues: false
  has_wiki: false
  has_downloads: false
  default_branch: master
  allow_squash_merge: false
  allow_merge_commit: true
  allow_rebase_merge: false

collaborators:
  - username: jkbuster
    permission: admin

branches:
  - name: master
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
        dismiss_stale_reviews: true
        require_code_owner_reviews: true
      required_status_checks: null
      enforce_admins: null
      restrictions: null
